### ISSUE TITLE
DEV-Version: Error in esp8266-install.sh

### ISSUE THREAD

**Issue by stritti** [thunderace/Esp8266-Arduino-Makefile#14]
In dev-branch there is currently a small bug: 

`./esp8266-install.sh: line 10: cd: esp8266/tools: No such file or directory`

I think there should be in esp8266-install.sh (line 10):

`cd ./esp8266-$ESP8266_VER/tools && ./get.py && cd ../..`

instead of:

`cd esp8266/tools && ./get.py && cd ../..`

**Comment by thunderace** [comment]
You're right. Fixed.
Thank you
