### ISSUE TITLE
Building with 2.5.2 programs are crashing.

### ISSUE THREAD

**Issue by mwinters-stuff** [thunderace/Esp8266-Arduino-Makefile#28]
Have tried with the new sdk, even the basic "blink" program is crashing at startup when using the makefile. If build and deploy with the arduino ide, the same program is working fine.

I have even tried the examples.

Reverting the SDK back to 2.4.2 the programs work from the make file..

Anyone else had  a problem?

**Comment by thunderace** [comment]
I will try tomorrow.

**Comment by thunderace** [comment]
It's related to the new esptool/upload scripts. A fix is on the way.

**Comment by thunderace** [comment]
Try the last commit

**Comment by mwinters-stuff** [comment]
Thanks, Will give it a try tonight - Thought I was going mad.. :+1:

**Comment by mwinters-stuff** [comment]
Working! Godo work, thanks.
