### ISSUE TITLE
upload_fs command incorrect

### ISSUE THREAD

**Issue by mwinters-stuff** [thunderace/Esp8266-Arduino-Makefile#30]
Getting around the other issue by commenting out the ifeq, The upload to file system fails with missing parameters..

Changed from
> $(ESPTOOL) $(ESPTOOL_VERBOSE) -cd $(UPLOAD_RESETMETHOD) -cb $(UPLOAD_SPEED) -cp $(SERIAL_PORT) -ca $(SPIFFS_START) -cf $(FS_IMAGE)
to:

> $(PYTHON) $(UPLOADTOOL) --chip esp8266 --port $(SERIAL_PORT) --baud $(UPLOAD_SPEED) write_flash $(SPIFFS_START) $(FS_IMAGE) --end

Seems to work good

**Comment by thunderace** [comment]
Fixed by 1e1ae93d3925d5340226dc1960fd420844cddb81
