### ISSUE TITLE
OTA Support

### ISSUE THREAD

**Issue by Sembiance** [thunderace/Esp8266-Arduino-Makefile#4]
In **esp8266Arduino.mk** you have hard coded your local IP in the 'OTA' target:
`$(ESPOTA) 192.168.1.184 8266 $(BUILD_OUT)/$(TARGET).bin`

If you change that line to this:
`$(ESPOTA) -i $(OTA_IP) -p $(OTA_PORT) -a $(OTA_AUTH) -f $(BUILD_OUT)/$(TARGET).bin`

Then anyone can use OTA simply by declaring the OTA_IP, OTA_PORT and OTA_AUTH variables in their own makefile. This is what I have done on my side and it works great!

Just wanted to also say THANK YOU for this project as I use it every day! Thanks!

**Comment by thunderace** [comment]
Done. Thank you.
