### ISSUE TITLE
Doesn't include libraries without a .cpp file

### ISSUE THREAD

**Issue by chuckwagoncomputing** [thunderace/Esp8266-Arduino-Makefile#7]
Some libraries, like Servo, have no <name>.cpp file in their src directory, only <name>.h.
These libraries are not found.

**Comment by thunderace** [comment]
It's because with Servo Library, the source code is under src/esp8266...
Try to add these 3 lines in esp8266Arduino.mk at line 108:
	$(ARDUINO_LIBS:%=$(ARDUINO_HOME)/libraries/%/src/*/*.c) \
	$(ARDUINO_LIBS:%=$(ARDUINO_HOME)/libraries/%/src/*/*.cpp) \
	$(ARDUINO_LIBS:%=$(ARDUINO_HOME)/libraries/%/src/*.h) \
tested with Servo library

**Comment by thunderace** [comment]
I have push the modification. Give it a try.

**Comment by chuckwagoncomputing** [comment]
Works fine now. I'd already made the modification before you suggested it, but I cloned again to test code for #6, so I went ahead and tried using the servo library. No errors, as expected.
